name: Android Release Export

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: 

jobs:
  android-release:
    runs-on: ubuntu-latest

    container:
      image: barichello/godot-ci:4.6.0-rc1

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Export Android Release
        run: |
          mkdir -p build
          godot --headless --export-release "Android" build/android-release.apk
        env:
          GODOT_ANDROID_KEYSTORE_PATH: release.keystore
          GODOT_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          GODOT_ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          GODOT_ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload Android build
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: build/
